version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker/username
    DOCKER_REGISTRY_PASSWORD: /docker/password
    DOCKER_REGISTRY_URL: /docker/registry/url
  variables:
    default: "default"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y python3 python3-pip docker
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Changing directory to 'toDeploy'..."
      - cd toDeploy
      - echo "Setting up environment..."
      - python manage.py makemigrations
      - python manage.py migrate
      - echo "Running test cases..."
      - python manage.py test
      - cd ..
  build:
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/django-print-name:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/django-print-name:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - "**/*"
